version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    networks:
      - backend
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=p07_social_network
      - MYSQL_USER=user
      - MYSQL_PASSWORD='123'
      - MYSQL_ROOT_PASSWORD=''
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - backend
networks:
  backend:
